// Generated by CoffeeScript 1.4.0
var idSequence;

idSequence = 0;

Object.defineProperty(Function.prototype, 'fing', {
  set: function(value) {},
  get: function() {
    var args, name, _i, _len, _ref;
    this.__id || (this.__id = ++idSequence);
    args = [];
    _ref = this.toString().match(/\((.*)\)\s{/)[1].split(', ');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      if (name) {
        args.push({
          name: name
        });
      }
    }
    return {
      type: 'prototype',
      name: this.name,
      args: args,
      id: this.__id,
      ref: "prototype:" + this.name + ":" + this.__id
    };
  }
});

Object.defineProperty(Object.prototype, 'fing', {
  get: function() {
    this.__id || (this.__id = ++idSequence);
    return {
      type: 'instance',
      name: this.constructor.name,
      args: this.constructor.fing.args,
      id: this.__id,
      ref: "instance:" + this.constructor.name + ":" + this.__id
    };
  }
});

module.exports = {};
