// Generated by CoffeeScript 1.4.0

Object.defineProperty(Function.prototype, 'fing', {
  set: function(value) {},
  get: function() {
    var args, name, _i, _len, _ref;
    args = [];
    _ref = this.toString().match(/\((.*)\)\s{/)[1].split(', ');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      if (name) {
        args.push({
          name: name
        });
      }
    }
    return {
      args: args
    };
  }
});

module.exports = {};
