// Generated by CoffeeScript 1.4.0

Object.defineProperty(Function.prototype, 'fing', {
  set: function(value) {},
  get: function() {
    return {
      args: []
    };
  }
});

module.exports = {};
