// Generated by CoffeeScript 1.4.0
var Stack;

module.exports = Stack = {
  trace: function(object) {
    var count, line, parts, skip, stack, _i, _len, _ref;
    stack = [];
    skip = 2;
    count = 0;
    _ref = Error.apply(this).stack.split('\n');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      line = _ref[_i];
      if (line === 'Error') {
        continue;
      }
      if (!(++count > skip)) {
        continue;
      }
      console.log(line);
      parts = line.match(/^.*at (.*)\((.*)\)/);
      stack.push({
        call: parts[1].trim()
      });
    }
    return stack;
  }
};
